/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FixRouteImport } from './routes/fix'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CostRouteImport } from './routes/cost'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FixRoute = FixRouteImport.update({
  id: '/fix',
  path: '/fix',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/faq': typeof FaqRoute
  '/fix': typeof FixRoute
  '/industries': typeof IndustriesRoute
  '/numbers': typeof NumbersRoute
  '/partners': typeof PartnersRoute
  '/problem': typeof ProblemRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/faq': typeof FaqRoute
  '/fix': typeof FixRoute
  '/industries': typeof IndustriesRoute
  '/numbers': typeof NumbersRoute
  '/partners': typeof PartnersRoute
  '/problem': typeof ProblemRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/faq': typeof FaqRoute
  '/fix': typeof FixRoute
  '/industries': typeof IndustriesRoute
  '/numbers': typeof NumbersRoute
  '/partners': typeof PartnersRoute
  '/problem': typeof ProblemRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cost'
    | '/faq'
    | '/fix'
    | '/industries'
    | '/numbers'
    | '/partners'
    | '/problem'
    | '/who-we-are'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cost'
    | '/faq'
    | '/fix'
    | '/industries'
    | '/numbers'
    | '/partners'
    | '/problem'
    | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cost'
    | '/faq'
    | '/fix'
    | '/industries'
    | '/numbers'
    | '/partners'
    | '/problem'
    | '/who-we-are'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CostRoute: typeof CostRoute
  FaqRoute: typeof FaqRoute
  FixRoute: typeof FixRoute
  IndustriesRoute: typeof IndustriesRoute
  NumbersRoute: typeof NumbersRoute
  PartnersRoute: typeof PartnersRoute
  ProblemRoute: typeof ProblemRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix': {
      id: '/fix'
      path: '/fix'
      fullPath: '/fix'
      preLoaderRoute: typeof FixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CostRoute: CostRoute,
  FaqRoute: FaqRoute,
  FixRoute: FixRoute,
  IndustriesRoute: IndustriesRoute,
  NumbersRoute: NumbersRoute,
  PartnersRoute: PartnersRoute,
  ProblemRoute: ProblemRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
